name: reddit-bot
on:
  schedule:
    # 2 déclenchements/jour (matin + soir) → en UTC
    # Exemple : 07:15 UTC (~09:15 Bruxelles), 18:15 UTC (~20:15 Bruxelles)
    - cron: "15 7 * * *"
    - cron: "15 18 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install praw

      - name: Run Reddit bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "LoufiArtBot/1.0 by u/loufisart"
          REDDIT_SUBREDDITS: "art,ArtistLounge"
          ASSETS_DIR: "./assets/posts"
        run: python reddit_bot_safe.py --oneshot
